### ISSUE TITLE
Create proposal about naming conventions for our github repositories

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/repo#1]
Create proposal about naming conventions for our github repositories

Related: https://github.com/kubewarden/policy-rust-template/issues/13

**Comment by ereslibre** [comment]
```text
* Proposal

Split Kubewarden in two different organizations: ~kubewarden~ and
~kubewarden-policies~. This makes it easier to separate all Kubewarden
components and policies.

There might even be a different set of maintainers depending on the
organization.

** Organizations

*** ~kubewarden~ organization

- Everything core to ~kubewarden~ goes in this organization.

| Repo                    | Type     |                                                          |
|-------------------------+----------+----------------------------------------------------------|
| ~automation~            |          |                                                          |
| ~docs~                  |          |                                                          |
| ~gjson~                 | Fork     |                                                          |
| ~gtmpl-rust~            | Fork     |                                                          |
| ~helm-charts~           |          |                                                          |
| ~krustlet~              | Fork     |                                                          |
| ~kubewarden-controller~ |          |                                                          |
| ~kubewarden.io~         |          |                                                          |
| ~kwctl~                 |          |                                                          |
| ~load-testing~          |          |                                                          |
| ~mdBook~                |          |                                                          |
| ~notify-policy-hub~     | Infra    | Move to ~kubewarden-policies~?                           |
| ~policy-evaluator~      |          |                                                          |
| ~policy-fetcher~        |          |                                                          |
| ~policy-hub~            | Infra    | Move to ~kubewarden-policies~?                           |
| ~go-policy-sdk~         |          |                                                          |
| ~rust-policy-sdk~       | SDK      |                                                          |
| ~swift-policy-sdk~      | SDK      |                                                          |
| ~policy-server~         |          |                                                          |
| ~repo~                  | git-repo | Split in two for ~kubewarden~ and ~kubewarden-policies~? |
| ~swift-wasm-runner~     |          |                                                          |
| ~UI~                    | UI       |                                                          |

*** ~kubewarden-policies~ organization

- By default, every project in this organization is a policy. Avoid
  having the ~-policy~ suffix on every policy, does not add value..
- Avoid ~allow~/~reject~ in names. Policies are already about
  allowing, rejecting or mutating.
- Templates have the ~-template~ suffix.
- Main topic of the policy goes first; makes it easier to discover
  what a policy is about.
- Pod Security Policies replacements may have the ~-psp~ suffix.

| Repo                                   | Type                      | New name                         |
|----------------------------------------+---------------------------+----------------------------------|
| ~gatekeeper-policy-template~           | GitHub Template           |                                  |
| ~go-policy-template~                   | GitHub Template           |                                  |
| ~ingress-policy~                       | Policy                    | ~ingress~                        |
| ~opa-policy-template~                  | GitHub Template           |                                  |
| ~pod-privileged-policy~                | Policy                    | ~pod-privileged~                 |
| ~pod-runtime-class-policy~             | Policy                    | ~pod-runtime-class~              |
| ~policy-disallow-service-loadbalancer~ | Policy                    | ~disallow-service-loadbalancer~  |
| ~policy-disallow-service-nodeport~     | Policy                    | ~disallow-serv-cenodeport~       |
| ~policy-rust-template~                 | ~cargo-generate~ Template | ~rust-policy-template~           |
| ~policy-user-group~                    | Policy                    | ~user-group~                     |
| ~psp-allow-privilege-escalation~       | Policy (PSP)              | ~allow-privilege-escalation-psp~ |
| ~psp-allowed-fsgroups~                 | Policy (PSP)              | ~fsgroups-psp~                   |
| ~psp-allowed-proc-mount-types~         | Policy (PSP)              | ~proc-mount-types-psp~           |
| ~psp-apparmor~                         | Policy (PSP)              | ~apparmor-psp~                   |
| ~psp-capabilities~                     | Policy (PSP)              | ~capabilities-psp~               |
| ~psp-flexvolume-drivers~               | Policy (PSP)              | ~flexvolume-drivers-psp~         |
| ~psp-host-namespaces~                  | Policy (PSP)              | ~host-namespaces-psp~            |
| ~psp-hostpaths-policy~                 | Policy (PSP)              | ~hostpaths-psp~                  |
| ~psp-selinux~                          | Policy (PSP)              | ~selinux-psp~                    |
| ~psp-sysctl-policy~                    | Policy (PSP)              | ~sysctl-psp~                     |
| ~psp-volumes-policy~                   | Policy (PSP)              | ~volumes-psp~                    |
| ~safe-annotations-policy~              | Policy                    | ~safe-annotations~               |
| ~safe-labels-policy~                   | Policy                    | ~safe-labels~                    |
| ~swift-policy-template~                | GitHub Template           |                                  |
| ~trusted-repos-policy~                 | Policy                    | ~trusted-repos~                  |
```

**Comment by viccuad** [comment]
Many thanks for the proposal :). A :+1:  from me!

I side with leaving `policy-hub`, `notify-policy-hub` outside of `kubewarden-policies` org.
I wonder if GH redirects work after several changes, or if we should move the repos to the new org first, and then rename.

Is there any migration path that needs to be followed besides the renaming of repos?
I suppose the policies' metadata needs to be updated, re-released, creating new images in https://github.com/orgs/kubewarden/packages and deleting the old ones if relevant. And then the policies need to be resubmitted to the Hub, removing the ones under the old names.

**Comment by ereslibre** [comment]
> Is there any migration path that needs to be followed besides the renaming of repos?

Yes, once we have settled on the layout that we want I'll follow up with all the changes needed for that to happen.

**Comment by ereslibre** [comment]
>  I wonder if GH redirects work after several changes, or if we should move the repos to the new org first, and then rename.

I don't know the real differences between rename & move or move & rename, and how that impacts assets in the GitHub registry -- are they also redirected?

In any case, as long as we are explicit about the change -- e.g. via a blog post -- to the new location I think we are fine.

**Comment by jvanz** [comment]
:+1 for the proposal.

> Also, is it possible to easily link to issues in a different org in the new GH beta projects?
I do not think so.

**Comment by viccuad** [comment]
then, I suppose that means we will have 2 project boards, one for policies, and one for core. We can create those empty "cards" in the core board, and keep tracking our project just there I suppose.

**Comment by kkaempf** [comment]
> then, I suppose that means we will have 2 project boards
I hope not. Two issue backlogs are fine, but we should have one prioritized development board.

**Comment by viccuad** [comment]
Agree. I vote for not opening a second project board in kubewarden-policies, and just creating "cards" with the links to issues in the current board then.

**Comment by kkaempf** [comment]
The current board is at org level, all repositories below the 'kubewarden' org can contribute issues to this project. No need to link :wink:

**Comment by flavio** [comment]
Personal list of things to be fixed:

- [ ] `ingress-policy`                                                        
- [ ] `pod-privileged-policy`                                                 
- [ ] `pod-runtime-class-policy`                                              
- [ ] `policy-disallow-service-loadbalancer` -> `service-loadbalancer-policy`     
- [ ] `policy-disallow-service-nodeport`     -> `service-nodeport-policy`         
- [ ] `policy-user-group`                    -> `user-group-policy`               
- [ ] `psp-allow-privilege-escalation`       -> `privilege-escalation-psp-policy` 
- [ ] `psp-allowed-fsgroups`                 -> `fsgroups-psp-policy`             
- [ ] `psp-allowed-proc-mount-types`         -> `proc-mount-types-psp-policy`     
- [ ] `psp-apparmor`                         -> `apparmor-psp-policy`             
- [ ] `psp-capabilities`                     -> `capabilities-psp-policy`         
- [ ] `psp-flexvolume-drivers`               -> `flexvolume-drivers-psp-policy`   
- [ ] `psp-host-namespaces`                  -> `host-namespaces-psp-policy`      
- [ ] `psp-hostpaths-policy`                 -> `hostpaths-psp-policy`            
- [ ] `psp-selinux`                          -> `selinux-psp-policy`              
- [ ] `psp-sysctl-policy`                    -> `sysctl-psp-policy`               
- [ ] `psp-volumes-policy`                   -> `volumes-psp-policy`              
- [ ] `safe-annotations-policy`                                               
- [ ] `safe-labels-policy`                                                    
- [ ] `trusted-repos-policy`

**Comment by flavio** [comment]
All done, closing the card
